### ISSUE TITLE
Much improved 2Checkout Driver

### ISSUE THREAD

**Issue by collizo4sky** [thephpleague/omnipay-2checkout#12]
Hi @amacneil and @kayladnls 

I wrote a much improved 2co gateway using the latest API paramters and support for payment via credit card token.

See it here https://github.com/collizo4sky/omnipay-2checkout

Note: the one here uses llagacy parameters (http://help.2checkout.com/articles/Knowledge_Article/Legacy-Parameter-Set) which include no support to pass in line items of products to puchase and obviously lack support for payment via credit card token.

I was hoping mine should replace this. and if No, the least thing to be done is include it in the [list of payment gateways](https://github.com/thephpleague/omnipay)

**Comment by collizo4sky** [comment]
@kayladnls what do you think?

**Comment by delatbabel** [comment]
Can we get some docblocks on the new gateway please? I think that incorporating it as a new gateway and deprecating the existing 2checkout gateway (but leaving it in place for anyone that's still using it) is probably the way to go.

**Comment by collizo4sky** [comment]
@delatbabel totally agree with that direction. 
I will get the docblocks added, add some documentation to the readme and let you know when it's done.

**Comment by collizo4sky** [comment]
Hey @delatbabel its done. https://github.com/collizo4sky/omnipay-2checkout

A pull request and an issue merged and fixed respectively :smile: 

Let me know when i can submit a PR for it inclusion among the list of gateway drivers.

**Comment by delatbabel** [comment]
Hi, yes this should be fine to submit to https://github.com/thephpleague/omnipay

**Comment by delatbabel** [comment]
@collizo4sky if your driver replaces this one then perhaps you can submit a PR for the REAME.md in this gateway announcing that it has been deprecated and pointing people to your own gateway.  In the mean time I will close this issue as the PR for the master repo has been merged.

**Comment by collizo4sky** [comment]
Done.
