### ISSUE TITLE
Support for refund

### ISSUE THREAD

**Issue by mpoiriert** [thephpleague/omnipay-2checkout#14]
It's seem from 2 checkout api that it does support refund

https://www.2checkout.com/documentation/api/sales/refund-invoice

Is there a reason it's not integrated in the gateway ?

If there is no reason why not I will probably do it where I work and submit a pull request.

From what I see there is no integration test ? So for unit test I just validate the input/outpu without really calling the 2checkout api ?

**Comment by delatbabel** [comment]
I believe that this gateway plugin is deprecated and no further changes are being made.  There is a later version that has been released.  See https://github.com/collizo4sky/omnipay-2checkout
