### ISSUE TITLE
Undefined property: Omnipay\TwoCheckout\Message\PurchaseResponse::$testendpoint

### ISSUE THREAD

**Issue by hillelcoren** [thephpleague/omnipay-2checkout#16]
I think the 'E' in testendpoint needs to be capitalized to testEndpoint. 

https://github.com/thephpleague/omnipay-2checkout/blob/b27d2823d052f5c227eeb29324bb564cfdb8f9af/src/Message/PurchaseResponse.php#L28

**Comment by barryvdh** [comment]
Thanks, fixed!
